doctrine:
    dbal:
        dbname: aaxis_test
        host: 127.0.0.1
        port: 5432
        driver: 'pdo_pgsql'
        server_version: '15'
        charset: UTF8
        default_table_options:
            charset: UTF8
            collate: UTF8_unicode_ci
        url: '%env(resolve:DATABASE_URL)%'
        profiling_collect_backtrace: '%kernel.debug%'
    orm:
        auto_generate_proxy_classes: true
        enable_lazy_ghost_objects: true
        report_fields_where_declared: true
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App